### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jbtule** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#4]
An old 4-clause BSD license really? I'm going to add to my marketing material  "This product includes tracking software developed by the Georg Kitz" :-P

**Comment by gekitz** [comment]
I will change the license asap ;) Had no time to look up and pick the right one ;)

**Comment by markrickert** [comment]
Georg,

Did you decide not to change the license? I personally love the idea of this library as an alternative to `[UIDevice currentDevice] uniqueIdentifier]` , but won't use it in production apps unless the license changes.

I prefer (in order):
- Public Domain
- MIT
- GNU v. 2
- Apache

Looks like this issue was closed without the license file ever changing. https://github.com/gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5/commits/master/license

Thanks,
-Mark

**Comment by gekitz** [comment]
I simply forgot to update it ;) Just check out the latest commit. Changed the license to MIT.

Cheers,
Georg
